#!/bin/bash

############### PYTHON 2.7 EXAMPLE 


function printCurrentDate {
python - <<END
import datetime
print datetime.datetime.now()
END
}

printCurrentDate

############### PYTHON 3.6 EXAMPLE 

function pathlibExample {
python3.6 - <<END
from pathlib import Path
p = Path('.')
print(p.absolute().as_posix())
END
}

pathlibExample
